---
- hosts: all
  become: yes
  tasks:
    - name: "yum install unzip"
      yum: name=unzip state=latest
    - name: Copy truncate_files.sh
      copy: src=tomcat-ansible/librenms-status.sh dest=/root mode=755
    - name: Run the script
      command: sh /root/librenms-status.sh
