---
- name: Download Tomcat
  become: yes
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.36/bin/apache-tomcat-8.0.36.tar.gz dest=/home/{{user}}/ timeout=1000 force=no owner={{user}} group={{user}}

- name: Extract archive
  become: yes
  unarchive: src=/home/{{user}}/apache-tomcat-8.0.36.tar.gz dest=/home/{{user}} copy=no group={{user}} owner={{user}} creates={{ tomcat_home }}

- name: Symlink install directory
  become: yes
  file: src={{ tomcat_home }} path=/usr/share/tomcat state=link
  ignore_errors: yes

- name: Change ownership of Tomcat installation
  become: yes
  file: path=/usr/share/tomcat/ owner={{user}} group={{user}} state=directory recurse=yes

- name: Delete Catalina
  become: yes
  file: path={{ tomcat_home }}/conf/Catalina state=absent
      
- name: set permission
  become: yes
  become_user: learning
  file: path={{ tomcat_home }}  mode=0755 owner={{user}} group={{user}} recurse=yes
  tags:
       - learning
       - language
       - config
       - total

- name: add templates for learning& language
  become: yes
  become_user: learning
  template: src={{ item.name }} dest={{ item.destination }}
  with_items:
    - { name: 'server.xml', destination: '/usr/share/tomcat/conf/' }
    - { name: 'catalina.j2', destination: '{{ tomcat_home }}/bin/catalina.sh' }
  tags:
       - learning
       - language

- name: add templates for  config
  become: yes
  become_user: learning
  template: src={{ item.name }} dest={{ item.destination }}
  with_items:
    - { name: 'server.xml', destination: '/usr/share/tomcat/conf/' }
    - { name: 'searchcatalina.j2', destination: '{{ tomcat_home }}/bin/catalina.sh' }
  tags:
       - config

- name: Install Tomcat init script
  become: yes
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=755
  tags:
       - learning
       - language
       - config
       - total

- name: set permission
  become: yes
  file: path={{ tomcat_home }}  mode=0755 owner={{user}} group={{user}} recurse=yes
  tags:
       - learning
       - language
       - config
       - total
